version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://root:123456@postgres:5432/vank_local
      NODE_ENV: development
      PORT: 3000
    ports:
      - "8080:3000"

  postgres:
    image: postgres:10.4
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: vank_local
